on:
  push:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: cache-go
        uses: actions/cache@v4
        with:
          path:
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - if: ${{ steps.cache-go.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: go mod tidy
      - run: go build
