name: Hello

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello ${{ inputs.target }}'
